name: Deploy VitePress Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

      # دریافت کد
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # نصب Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm




      # نصب پکیج‌ها
      - name: Install dependencies
        run: pnpm install --frozen-lockfile


      # Build VitePress
      - name: Build documentation
        run: pnpm docs:build


      # Deploy FTP
      - name: Upload to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:

          server: ${{ secrets.FTP_SERVER }}

          username: ${{ secrets.FTP_USERNAME }}

          password: ${{ secrets.FTP_PASSWORD }}

          port: 21

          protocol: ftp

          local-dir: .vitepress/dist/

          server-dir: /

          dangerous-clean-slate: true